use std::{
    env,
    fs,
    io::Write,
    path::{Path, PathBuf},
};

fn sanitize_test_name(file_name: &str) -> String {
    let mut out = String::new();
    for ch in file_name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }

    while out.contains("__") {
        out = out.replace("__", "_");
    }

    out = out.trim_matches('_').to_string();

    if out.is_empty() {
        out = "fixture".to_string();
    }

    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert_str(0, "fixture_");
    }

    out
}

fn main() {
    println!("cargo:rerun-if-changed=tests/fixtures");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fixtures_dir = manifest_dir.join("tests").join("fixtures");

    let mut fixtures = fs::read_dir(&fixtures_dir)
        .unwrap_or_else(|e| panic!("Failed to read fixtures dir {}: {e}", fixtures_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
        .collect::<Vec<PathBuf>>();

    fixtures.sort();

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("generated_fixture_tests.rs");

    let mut f = fs::File::create(&dest_path)
        .unwrap_or_else(|e| panic!("Failed to create {}: {e}", dest_path.display()));

    writeln!(
        f,
        "// @generated by build.rs - do not edit by hand\n"
    )
    .unwrap();

    for path in fixtures {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("fixture.json");

        let stem = Path::new(file_name)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("fixture");

        let fn_name = format!("fixture_{}", sanitize_test_name(stem));
        let rel_path = format!("tests/fixtures/{file_name}");

        writeln!(
            f,
            "#[test]\nfn {fn_name}() {{\n    run_fixture_file(\"{rel_path}\");\n}}\n"
        )
        .unwrap();
    }
}
